services:
  resizer:
    image: irazz/resizer:latest
    ports:
      - "3000:3000"
    environment:
      - UPSTASH_REDIS_URL=https://novel-titan-xxxx.upstash.io
      - UPSTASH_REDIS_TOKEN=AXB9Axxxxxxxxx
    restart: unless-stopped